#ifndef LOSEMYMIND_CLIENTPROTOCOLDEFINES_H
#define LOSEMYMIND_CLIENTPROTOCOLDEFINES_H

#include "FoundationKit/Base/Types.h"
USING_NS_FK;

#define  CLIENT_LOGIN  1000
#define  CLIENT_CHAT  1001


#endif // LOSEMYMIND_CLIENTPROTOCOLDEFINES_H
